import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const monument = localFont({
  src: [
    {
      path: "../fonts/MonumentExtended-Regular.woff2",
      weight: "regular",
      style: "italic",
    }
  ],
  variable: "--monument",
});

const satoshi = localFont({
  src: [
    {
      path: "../fonts/Satoshi-Regular.woff2",
      weight: "regular",
      style: "italic",
    },
    {
      path: "../fonts/Satoshi-Medium.woff2",
      weight: "regular",
      style: "italic",
    },
    {
      path: "../fonts/Satoshi-Bold.woff2",
      weight: "bold",
      style: "normal",
    }
  ],
  variable: "--satoshi",
});

export const metadata: Metadata = {
  title: "Creon Frontend Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${monument.className} ${satoshi.className}`}>
      <body>{children}</body>
    </html>
  );
}
